require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'bin/onetime-jobs'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'bin/yarn'
    - 'config.ru'
    - 'db/schema.rb'
    - 'Rakefile'
    - 'vendor/**/**'
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude: ['config/environments/production.rb']

Metrics/AbcSize:
  Exclude: ['db/migrate/*']

Metrics/BlockLength:
  Exclude:
    - 'db/seeds.rb'
    - 'config/environments/development.rb'
    - 'config/routes.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude: ['test/**/*']

Metrics/MethodLength:
  Exclude: ['db/migrate/*']

Metrics/ModuleLength:
  Max: 120

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude: ['bin/onetime-jobs/*']

Naming/InclusiveLanguage:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Rails:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20210824111007_create_active_storage_variant_records.active_storage.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/PluckId:
  Enabled: true

Rails/RenderInline:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/20210824111006_add_service_name_to_active_storage_blobs.active_storage.rb'

Rails/UniqBeforePluck:
  EnforcedStyle: aggressive

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/application_controller_renderer.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/cookies_serializer.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/mime_types.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/puma.rb'

Style/StringLiterals:
  Exclude:
    - 'config/puma.rb'
    - 'config/environments/production.rb'
