versions:
  ol: 7.5.1
  proj4: 2.9.0
  vertical_tabs: 1.2.2
  textresizer: 1.1.0

javascripts:
  ol.js: https://cdn.jsdelivr.net/npm/ol@v<%= versions[:ol] %>/dist/ol.js
  proj4js.js: https://cdn.jsdelivr.net/npm/proj4@<%= versions[:proj4] %>/dist/proj4.js
  jquery.ui.touch-punch.js: https://raw.githubusercontent.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.js
  jquery.ui.touch-punch.min.js: https://raw.githubusercontent.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js
  jquery.textresizer.js: https://raw.githubusercontent.com/mariojvargas/jquery-textresizer/<%= versions[:textresizer] %>/jquery.textresizer.js
  jquery.textresizer.min.js: https://raw.githubusercontent.com/mariojvargas/jquery-textresizer/<%= versions[:textresizer] %>/jquery.textresizer.min.js
  ol-ext.js: https://cdn.jsdelivr.net/gh/Viglino/ol-ext@master/dist/ol-ext.js
  ol-ext.min.js: https://cdn.jsdelivr.net/gh/Viglino/ol-ext@master/dist/ol-ext.min.js
  d3-v4.js: https://d3js.org/d3.v4.js
  d3-v4.min.js: https://d3js.org/d3.v4.min.js
  billboard.js: https://raw.githubusercontent.com/naver/billboard.js/1.2.0/dist/billboard.js
  billboard.min.js: https://raw.githubusercontent.com/naver/billboard.js/1.2.0/dist/billboard.min.js

stylesheets:
  ol.css: https://cdn.jsdelivr.net/npm/ol@v<%= versions[:ol] %>/ol.css
  ol-ext.css: https://cdn.jsdelivr.net/gh/Viglino/ol-ext@master/dist/ol-ext.css
  ol-ext.min.css: https://cdn.jsdelivr.net/gh/Viglino/ol-ext@master/dist/ol-ext.min.css
