development: &default
  urls:
    ks_server_url: <%= ENV.fetch('KS_SERVER_URL', 'http://localhost:3000') %>
    ks_backend_vorgang_url: https://klarschiff.de/backend/vorgang/%s
    ks_demo_url: https://klarschiff.de
    ks_github_url: https://github.com/bfpi/klarschiff-field_service
    font_origin_url: https://www.paratype.com
    font_license_url: /resources/fonts/license.txt
    not_content_two_url: https://polizei.mvnet.de/ssl/g8wache/cmswem/index.php?task=iw_anzeige
    not_content_three_url: http://rathaus.rostock.de/sixcms/detail.php?template=seite_umweltamt_wasser_boden_alarmdienst_de&_sid1=&_sid2=rostock_01.c.198934.de&_sid3=39237&_sid4=39245

  client: &default_client
    relative_url_root: /
    animate_refresh: 6
    service_code:
    key: hro
    login_required: false
    multi_requests_enabled: false
    name: Klarschiff
    city_long: Demostadt
    city_short: Demo
    resources_path: /srv/www/htdocs/klarschiff_resources/
    resources_url: https://demo.klarschiff.de/resources/
    resources_overview_path: /srv/www/htdocs/klarschiff_resources/requests/
    logo_url: /resources/images/logo.png
    observations_area_limit: 35
    recent_requests: 6
    recent_requests_per_row: 2
    new_icon_anchor_x: 16
    new_icon_anchor_y: 50
    service_type_idea: true
    service_type_problem: true
    skip_type_selection: false
    default_type:
    show_social_icons: true
    show_email:
    show_abuses:
    show_votes:
    show_create_comment:
    show_comments:
    show_edit_request:
    show_edit_status:
    show_protocol:
    show_notes:
    show_trust:
    show_d3_document_url:
    show_status_updates_for_supporter:
    additional_content: false
    start_date: 28.03.2012
    supported_file_types: image/png,image/jpeg
    max_image_size: 5242880
    show_privacy_policy: false

  static_pages:
    contact: false
    news: false
    participation: false
    promotion: false

  vote:
    min_requirement: 20

  resource_servers:
    city_sdk:
      site: https://klarschiff.de/citysdk/
      format: :json
      api_key: 1234567890abcdefghijklmnopqrstuv

  address_search:
    url: https://geo.sv.rostock.de/geocodr/query?
    api_key:
    localisator: rostock
    search_request_id_enabled: true

  geocodr:
    address_object_group: Adresse HRO
    address_search_class: address_hro
    api_key: 1234567890abcdefghijklmnopqrstuv
    localisator: rostock # darf leer sein
    parcel_object_group: Flurstück
    parcel_search_class: parcel
    places_object_group: Adresse
    places_search_class: address
    property_owner_object_group: Flurstückseigentümer
    property_owner_search_class: property_owner
    proxy:
    url: https://geo.sv.rostock.de/geocodr/query?
    search_request_id_enabled: true

  protocol_mail:
    recipient: recipient@klarschiff.de
    sender: sender@klarschiff.de
    smtp:
      host: smtp.klarschiff.de
      starttls_enabled: false
      username: benutzer
      password: passwort

  map:
    show_trust: true
    overlap_layers: false
    scale_bar: false
    default_requests_states: PENDING, RECEIVED, IN_PROCESS, PROCESSED, REJECTED
    center: [1343496, 7197537]
    tile_layers:
      -
        id: karte
        url: https://www.orka-mv.de/geodienste/orkamv/tiles/1.0.0/orkamv/GLOBAL_WEBMERCATOR/{z}/{x}/{y}.png
        url_statistics: https://www.orka-mv.de/geodienste/orkamv/tiles/1.0.0/orkamv-graustufen/GLOBAL_WEBMERCATOR/{z}/{x}/{y}.png
        visible: true
        attribution: >
          Kartenbild © Hanse- und Universitätsstadt Rostock (<a rel="license" target="_blank" href="https://creativecommons.org/licenses/by/4.0/deed.de">CC BY 4.0</a>) | Kartendaten © OpenStreetMap (<a rel="license" target="_blank" href="https://opendatacommons.org/licenses/odbl/">ODbL</a>) und LkKfS-MV
      -
        id: luftbild
        url: https://geo.sv.rostock.de/geodienste/luftbild_mv-20/tiles/1.0.0/hro.luftbild_mv-20.luftbild_mv-20/GLOBAL_WEBMERCATOR/{z}/{x}/{y}.png
        visible: false
        attribution: >
          Luftbild © <a rel="license" target="_blank" href="https://www.geoportal-mv.de/portal/Geowebdienste">GeoBasis-DE/M-V</a>
    wms_layers:
      -
        id: poi
        url: https://geo.sv.rostock.de/geodienste/klarschiff-poi/wms?
        projection: EPSG:3857
        content: hro.klarschiff-poi.abfallbehaelter,hro.klarschiff-poi.ampeln,hro.klarschiff-poi.beleuchtung,hro.klarschiff-poi.brunnen,hro.klarschiff-poi.denkmale,hro.klarschiff-poi.hundetoiletten,hro.klarschiff-poi.kabelverteilerschraenke,hro.klarschiff-poi.recyclingcontainer,hro.klarschiff-poi.sitzgelegenheiten,hro.klarschiff-poi.sperrmuelltermine_oeffentlich,hro.klarschiff-poi.gemeinde-hro-invers
        format: image/png
        visible: true
    tracking_options:
      enable_high_accuracy: true
      timeout: 30000
      maximum_age: 50000
    zoom:
      initial: 12
      max: 19
      min: 12
    resolution: false

  request:
    permissable_states:
      - IN_PROCESS
      - PROCESSED
      - REJECTED

  auto_refresh:
    timeout: 180000

test:
  <<: *default
  client:
    <<: *default_client
    login_required: false

alpha:
  <<: *default

consolidation:
  <<: *default

production:
  <<: *default
