urls:
  ks_frontend_search_url: https://klarschiff-test/search/server.php
  ks_server_url: https://klarschiff-test
  ks_frontend_imprint_url: https://klarschiff-test/static/imprint
  ks_backend_vorgang_url: https://klarschiff-test/backend/vorgang/%s
  ks_demo_url: https://klarschiff-test
  ks_github_url: https://github.com/bfpi/klarschiff-field_service
  font_origin_url: https://www.paratype.com
  font_license_url: /resources/fonts/license.txt

client:
  animate_refresh: 10
  service_code:
  key: hro
  login_required: true
  multi_requests_enabled: true
  name: Klarschiff
  city_long: Universitätsstadt Muggensturm
  city_short: Muggensturm
  resources_path: /var/www/html/hro/resources
  logo_url: /resources/images/logo.png
  show_email:
  show_abuses:
  show_votes:
  show_create_comment:
  show_comments:
  show_edit_request:
  show_edit_status:
  show_protocol:
  show_notes:
  show_trust:
  additional_content:

vote:
  min_requirement: 20

ldap:
  host: klarschiff-test
  username: uid=admin
  password: admin
  port: 636
  encryption: :simple_tls
  users:
    attributes_mapping: id=uid,name=cn,email=mail
    base: ou=users,ou=klarschiff,ou=SV
  groups:
    base: ou=groups,ou=klarschiff,ou=SV
    search_pattern: (&(objectClass=groupOfNames)(o=<groupname>)(member=%s))

resource_servers:
  city_sdk:
    site: https://klarschiff-test/citysdk/
    format: :json
    api_key: <API-Key>

protocol_mail:
  recipient: recipient@klarschiff.de
  sender: sender@klarschiff.de
  smtp:
    host: smtp.klarschiff.de
    starttls_enabled: false
    username: benutzer
    password: passwort

map:
  show_trust: true
  default_requests_states: PENDING, RECEIVED, IN_PROCESS, PROCESSED, REJECTED
  center: [312900, 5997281]
  mv_bbox_25833: [206885, 5890624, 460857, 6060841]
  extent: [271264, 5938535, 356804, 6017573]
  wmts_layers:
    -
      url: https://www.orka-mv.de/geodienste/orkamv/wmts/orkamv/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.png
      content: orkamv
      matrix_set: epsg_25833
      format: png
      request_encoding: REST
      tilegrid_origin: [-464849.38, 6310160.14]
      resolutions: [27.024570517098006, 19.109257071294042, 13.512285258549001, 9.55462853564702, 6.7561426292745, 4.77731426782351, 3.3780713146372494, 2.3886571339117544, 1.6890356573186245, 1.1943285669558772, 0.8445178286593122, 0.5971642834779384, 0.422258914329656, 0.29858214173896913, 0.21112945716482798, 0.14929107086948457]
      matrix_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
      extent: [271264, 5938535, 356804, 6017573]
      visible: true
      attribution: >
        Kartenbild © Hansestadt Rostock
        (<a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.de" target="_blank" style="color: #006CB7; text-decoration:none;">CC BY 4.0</a>) |
        Kartendaten © <a href="http://www.openstreetmap.org" target="_blank" style="color: #006CB7; text-decoration: none;">OpenStreetMap</a>
        (<a rel="license" href="http://opendatacommons.org/licenses/odbl" target="_blank" style="color: #006CB7; text-decoration: none;">ODbL</a>)
        und LkKfS-MV
    -
      url: https://geo.sv.rostock.de/geodienste/luftbild_mv-40/wmts/hro.luftbild_mv-40.luftbild_mv-40/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.png
      content: hro.luftbild_mv-40.luftbild_mv-40
      matrix_set: epsg_25833
      format: png
      request_encoding: REST
      tilegrid_origin: [-464849.38, 6310160.14]
      resolutions: [27.024570517098006, 19.109257071294042, 13.512285258549001, 9.55462853564702, 6.7561426292745, 4.77731426782351, 3.3780713146372494, 2.3886571339117544, 1.6890356573186245, 1.1943285669558772, 0.8445178286593122, 0.5971642834779384, 0.422258914329656, 0.29858214173896913, 0.21112945716482798, 0.14929107086948457]
      matrix_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
      extent: [271264, 5938535, 356804, 6017573]
      visible: false
      attribution: © GeoBasis-DE/M-V
  wms_layers:
    -
      url: https://geo.sv.rostock.de/geodienste/klarschiff-poi/wms?
      projection: EPSG:25833
      content: hro.klarschiff-poi.abfallbehaelter,hro.klarschiff-poi.ampeln,hro.klarschiff-poi.beleuchtung,hro.klarschiff-poi.brunnen,hro.klarschiff-poi.denkmale,hro.klarschiff-poi.hundetoiletten,hro.klarschiff-poi.recyclingcontainer,hro.klarschiff-poi.sitzgelegenheiten,hro.klarschiff-poi.sperrmuelltermine
      format: image/png
      extent: [271264, 5938535, 356804, 6017573]
      visible: true
  tracking_options:
    enable_high_accuracy: true
    timeout: 3000
    maximum_age: 5000
  zoom:
    initial: 5
    max: 15
    min: 5

request:
  permissable_states:
    - IN_PROCESS
    - PROCESSED
    - REJECTED

auto_refresh:
  timeout: 60000
