name: Stylesheets

on:
  - workflow_dispatch

jobs:
  stylelint:
    name: CSS files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: bin/stylelint
