name: ERB Templates

on:
  - workflow_dispatch

permissions:
  contents: read

env:
  RAILS_ENV: test

jobs:
  erblint:
    name: ERB files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run ERB Lint
        run: bin/erblint
