name: Rails Tests

on:
  - workflow_dispatch

env:
  RAILS_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Prepare Assets
        run: bundle exec rails assets:precompile
      - name: Run Rails Tests
        run: bundle exec rails test -b -d

